---
- name: Install fail2ban
  apt:
    name: fail2ban
    cache_valid_time: 3600
    state: latest

- name: Configure fail2ban sshd
  ansible.builtin.copy:
    src: "jail.local"
    dest: "/etc/fail2ban/jail.local"
    owner: root
    group: root
    mode: "644"
  notify: restart fail2ban

- name: Enable fail2ban service
  ansible.builtin.systemd:
    name: fail2ban
    enabled: yes
    state: started