---
 - name: Disable password authentication
   lineinfile:
     dest: "{{sshd_config}}"
     regexp: '^(#\s*)?PasswordAuthentication '
     line: 'PasswordAuthentication no'
   notify: restart sshd

 - name: Disable empty password login
   lineinfile:
     dest: "{{sshd_config}}"
     regexp: '^#?PermitEmptyPasswords'
     line: 'PermitEmptyPasswords no'
   notify: restart sshd

 - name: Disable root password login
   lineinfile:
     dest: "{{sshd_config}}"
     regexp: '^#?PermitRootLogin'
     line: 'PermitRootLogin without-password'
   notify: restart sshd

 - name: Set user authorized_key
   authorized_key:
     user: "{{ansible_user}}"
     state: present
     key: "{{ lookup('file', '../../../secrets/sshkey.pub') }}"
